<?php
/*
$outputs = array('array','json');
if (!isset($_GET['output']) OR !in_array($_GET['output'],$outputs))
	echo '<h2 style="color: red">You need to specify a output format.</h2>';
$output = strval($_GET['output']);
*/

require_once(realpath(dirname(__FILE__).'/../../..').'/wp-load.php');

$args = array(
	'type'                      => 'post'   // Type of category to retreive: post OR link
	,'child_of'                 => 0        // Display all categories that are descendants
	,'orderby'                  => 'name'   // Sort categories: id, name, slug, count, group
	,'order'                    => 'ASC'    // Sort order for categories
	,'hide_empty'               => false    // Toggles the display of categories with no posts
	,'hierarchical'             => false    // When true, the results will include sub-categories that are empty, as long as those sub-categories have sub-categories that are not empty
	//,'exclude'                  => '1'      // Excludes one or more categories from the list generated by wp_list_categories 
	//,'include'                  => '2'      // Only include certain categories in the list generated by wp_list_categories
	//,'number'                   => '5'      // The number of categories to return
	,'pad_counts'               => false      // Calculates link or post counts by including items from child categories.
);
$categories = get_categories($args);

$myCategories = array();
foreach($categories as $key => $category)
{
	$myCategories[$key]['name'] = $category->name;
	$myCategories[$key]['link'] = get_category_link($category->term_id);
	$myCategories[$key]['description'] = $category->description;
	$myCategories[$key]['count'] = $category->count;
}

/*if ($output == 'json')
{*/
	//header('Content-type: text/javascript');
	header('Content-type: application/json');
	echo json_encode($myCategories);
/*}
elseif ($output == 'array')*/
//echo $return;
